const mongoose=require("mongoose");
const lectureSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
    },
    branch:{
        type:String,
        required:true,
    },
    year :{
        type:String,
        required:true,
    },
    subject:{
        type:String,
        required:true,
    },
    topic:{
        type:String,
        required:true,
    },
    learningGoal:{
        type:String,
        required:true,
    },
    channel:{
        type:String,
        required:true,
    },
    instructor:{
        type:String,
        required:true,
    },
    duration:{
        type:String,
        required:true,
    },
    rating:{
        type:Number,
        required:true,
    },
    views:{
        type:String,
        required:true,
    },
    language:{
        type:String,
        required:true,
    },
    difficulty:{
        type:String,
        required:true,
    },
    youTubeLink:{
        type:String,
        required:true,
    },
    notes:{
        type:String,
        required:true,
    },
    quiz:[{
        question:{
        type:String,
        required:true,
        },
        options:{
        type:[String],
        required:true,
        },
        answer:{
            type:String,
            required:true,
        },
    },
    ],
    summary:{
        type:String,
        required:true,
    },
});
const Lecture=mongoose.model("Lecture",lectureSchema);
module.exports=Lecture;